name: Zotero Android Release Tracker

on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-release:
    name: Check for new Zotero Android release
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.check_release.outputs.new_release }}
      release_tag: ${{ steps.check_release.outputs.release_tag }}
    steps:
      - name: Get latest Zotero tag
        id: check_release
        run: |
          # Get the latest tag from Zotero's repo (sorted by version number)
          LATEST_TAG=$(curl -s https://api.github.com/repos/zotero/zotero-android/tags | jq -r '.[0].name')
          echo "Latest Zotero tag: $LATEST_TAG"
          
          # Get our last built tag, default to 'none' if no tags exist
          LAST_BUILT=$(curl -s https://api.github.com/repos/${{ github.repository }}/tags | jq -r '.[0].name // "none"')
          echo "Our last built tag: $LAST_BUILT"
          
          if [ "$LAST_BUILT" = "none" ] || [ "$LAST_BUILT" != "$LATEST_TAG" ]; then
            echo "New release detected"
            echo "new_release=true" >> $GITHUB_OUTPUT
            echo "release_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          else
            echo "No new release"
            echo "new_release=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-release
    if: ${{ needs.check-release.outputs.new_release == 'true' }}
    name: Build New Release
    runs-on: ubuntu-latest
    steps:
      - name: Debug Initial State
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Create and Debug Working Directory
        run: |
          mkdir -p zotero-android
          echo "Created directory structure:"
          ls -la
          echo "Entering zotero-android directory"
          cd zotero-android
          echo "Now in: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Clone Zotero Android repository
        run: |
          echo "Before clone - Current directory: $(pwd)"
          git clone --recursive https://github.com/zotero/zotero-android.git .
          echo "After clone - Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Scripts directory contents:"
          ls -la scripts/ || echo "scripts directory not found!"
          git checkout ${{ needs.check-release.outputs.release_tag }}
          echo "After checkout - Directory contents:"
          ls -la
        working-directory: zotero-android

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Debug Before Python Scripts
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Scripts directory contents (if exists):"
          ls -la scripts/ || echo "scripts directory not found!"
        working-directory: zotero-android

      - name: Grant execute permission for Python scripts
        run: |
          if [ -f "scripts/bundle_translators.py" ]; then
            echo "bundle_translators.py exists"
            chmod +x scripts/bundle_translators.py
          else
            echo "bundle_translators.py not found!"
            echo "Current directory: $(pwd)"
            echo "Directory contents:"
            ls -la
          fi
          
          if [ -f "scripts/bundle_translation.py" ]; then
            echo "bundle_translation.py exists"
            chmod +x scripts/bundle_translation.py
          else
            echo "bundle_translation.py not found!"
          fi
        working-directory: zotero-android

      - name: Execute bundling scripts
        run: |
          echo "Current directory before running scripts: $(pwd)"
          python3 scripts/bundle_translators.py
          python3 scripts/bundle_translation.py
        working-directory: zotero-android

      - name: Grant execute permission for gradlew
        run: |
          echo "Current directory: $(pwd)"
          echo "Checking for gradlew:"
          ls -la gradlew || echo "gradlew not found!"
          chmod +x gradlew
        working-directory: zotero-android

      - name: Download Android dependencies
        run: ./gradlew androidDependencies --no-configuration-cache
        working-directory: zotero-android

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: zotero-android

      - name: Debug APK Output Directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Checking APK output directory:"
          ls -la app/build/outputs/apk/debug/ || echo "APK output directory not found!"
        working-directory: zotero-android

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.check-release.outputs.release_tag }}
          name: Zotero Android ${{ needs.check-release.outputs.release_tag }}
          makeLatest: true
          body: |
            Built from Zotero Android tag ${{ needs.check-release.outputs.release_tag }}
            Source: https://github.com/zotero/zotero-android/tree/${{ needs.check-release.outputs.release_tag }}
          artifacts: "zotero-android/app/build/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
